### PR TITLE
docs: add the installation guide with aqua

### LINKED ISSUE #34: Add the installation guide with aqua to the document
Hi, thank you for your great project!

We suggest to add the installation guide with aqua to the document.
[aqua](https://aquaproj.github.io/) is a declarative CLI Version Manager.
You can install this tool with aqua.

```sh
aqua init # Create aqua.yaml
aqua g -i hirosassa/ksnotify # Add this tool to aqua.yaml
aqua i # Install tools
```

For the detail of aqua, please see [the official document](https://aquaproj.github.io/).

We expect you can just copy and paste the following guide to your document.

---

## Install with aqua

You can install this tool with [aqua](https://aquaproj.github.io/).

```sh
aqua g -i hirosassa/ksnotify # Add hirosassa/ksnotify to aqua.yaml
```

---

Thank you.

_This issue was created automatically by script. For the detail, please see [here](https://github.com/orgs/aquaproj/discussions/2312#discussioncomment-7225546)._

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
Close #34

### CODE REVIEW

**Review by hirosassa — APPROVED** [review]
Thanks again!

**Comment by suzuki-shunsuke** [comment]
CI failed, but the error has nothing to do with the change of this pull request.

https://github.com/hirosassa/ksnotify/actions/runs/6451347195/job/17521863323?pr=35

```
Run cargo clippy -- -D warnings -W clippy::nursery
    Checking ksnotify v0.1.8 (/home/runner/work/ksnotify/ksnotify)
error: redundant pattern matching, consider using `is_ok()`
  --> src/config.rs:[8](https://github.com/hirosassa/ksnotify/actions/runs/6451347195/job/17521863323?pr=35#step:6:9)2:33
   |
82 |         let suppress_skaffold = matches!(env::var("KSNOTIFY_SUPPRESS_SKAFFOLD"), Ok(_));
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `env::var("KSNOTIFY_SUPPRESS_SKAFFOLD").is_ok()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_pattern_matching
   = note: `-D clippy::redundant-pattern-matching` implied by `-D warnings`

error: redundant pattern matching, consider using `is_ok()`
  --> src/config.rs:83:21
   |
83 |         let patch = matches!(env::var("KSNOTIFY_PATCH"), Ok(_));
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `env::var("KSNOTIFY_PATCH").is_ok()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_pattern_matching

error: could not compile `ksnotify` (bin "ksnotify") due to 2 previous errors
Error: Process completed with exit code [10](https://github.com/hirosassa/ksnotify/actions/runs/6451347195/job/17521863323?pr=35#step:6:11)1.
```

**Comment by hirosassa** [comment]
Yeah, I agree with you, so I'll merge this PR. 
I'll fix this problem in another PR 👍

**Comment by suzuki-shunsuke** [comment]
Thank you!

**Pull request merged**
